### ISSUE TITLE
Proper configuration steps for repo

### ISSUE THREAD

**Issue by pwolfram** [doutriaux1/mpas-tst#7]
Presumably there are certain requirements for the repository for the CI-bots to be used.  

 1. Wiki needs to be enabled
 2. Some github service needs to be enabled
 3. More???

Once the wiki is written some webhook on github's end needs to provide the green check / red x, e.g., for a pull request.  

A recommendation on how to set this up would be really helpful.  I'm happy to update the `README.md` following our discussion as an action item on this issue.

**Comment by doutriaux1** [comment]
@pwolfram actually the wiki are only needed to post thel ogs, but in the future wemight want to replace it with a local website?
no github services needed. Only a token (to write to statuses). Here again it can be later expanded to post to some other services (like bitbucket, etc...)

**Comment by pwolfram** [comment]
Thanks @doutriaux1, I think the wiki is fine for the logs.  The step I'm stuck on is how to get this integrated so that each PR provides the green check / red x.  

My current integration settings look like

![screenshot 2017-05-01 08 11 19](https://cloud.githubusercontent.com/assets/4295853/25581580/f2d7cab8-2e45-11e7-9156-8811249d06b6.png)

so I would anticipate that I need to do something here to get this to work properly too.

Can you please clarify what I need to do on the repo settings end to get all this to work?

**Comment by pwolfram** [comment]
@doutriaux1, to summarize: what were the settings for the repo to get the ci-bots to work properly on PRs?  Thanks!

**Comment by doutriaux1** [comment]
@pwolfram all you need is a personal token that you put in the josn file, I updated the README.md file.

**Comment by doutriaux1** [comment]
see: https://github.com/UV-CDAT/ci-bots/blob/master/README.md

**Comment by pwolfram** [comment]
Perfect, @doutriaux1!  Please see https://github.com/MPAS-Dev/MPAS-Analysis/pull/201/commits. I'm closing because this issue has been resolved.

**Comment by pwolfram** [comment]
Final question here -- are you opposed to me adding more detail about the requirements for the personal token?  I didn't have push access enable at first, which obviously caused the problem.  We may want to be explicit about the key attributes needed to get the personal access token set up correctly.

Thoughts on this issue @doutriaux1?

**Comment by doutriaux1** [comment]
@pwolfram I'm never opposed to free work that improve the software! 😜 
Feel free to submit as many PR as you wish.
