### ISSUE TITLE
Flushing / removal of custom checks

### ISSUE THREAD

**Issue by pwolfram** [doutriaux1/mpas-tst#9]
It appears that it may be possible to have a pending check that remains a yellow circle.

Is there some way to flush the custom checks, e.g., what if a check doesn't update properly and is effectively hung at a yellow circle?  Can we fix this type of confusing situation?

**Comment by doutriaux1** [comment]
@pwolfram I guess if you kill the cibot in the middle the test then it will never update the statuses

I will add an option to force a status (but it will also be written on github that it was a forced status update)

**Comment by pwolfram** [comment]
Awesome, thanks @doutriaux1!

**Comment by pwolfram** [comment]
Note, if the hash is changed and the test rerun, this isn't an issue so this is probably good to have, but not necessarily something critically needed because of this work-around.  It would just make things cleaner.

**Comment by doutriaux1** [comment]
fix by #10
